# GoReleaser configuration for vesctl CLI
# Documentation: https://goreleaser.com

version: 2

project_name: vesctl

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: vesctl
    binary: vesctl
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/robinmordasiewicz/vesctl/cmd.Version={{.Version}}
      - -X github.com/robinmordasiewicz/vesctl/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/robinmordasiewicz/vesctl/cmd.BuildDate={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: robinmordasiewicz
    name: vesctl
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## vesctl {{ .Version }}

    ### Installation

    **macOS (Apple Silicon)**
    ```bash
    curl -LO https://github.com/robinmordasiewicz/vesctl/releases/download/{{ .Tag }}/vesctl_{{ .Version }}_darwin_arm64.tar.gz
    tar -xzf vesctl_{{ .Version }}_darwin_arm64.tar.gz
    sudo mv vesctl /usr/local/bin/
    ```

    **macOS (Intel)**
    ```bash
    curl -LO https://github.com/robinmordasiewicz/vesctl/releases/download/{{ .Tag }}/vesctl_{{ .Version }}_darwin_amd64.tar.gz
    tar -xzf vesctl_{{ .Version }}_darwin_amd64.tar.gz
    sudo mv vesctl /usr/local/bin/
    ```

    **Linux (amd64)**
    ```bash
    curl -LO https://github.com/robinmordasiewicz/vesctl/releases/download/{{ .Tag }}/vesctl_{{ .Version }}_linux_amd64.tar.gz
    tar -xzf vesctl_{{ .Version }}_linux_amd64.tar.gz
    sudo mv vesctl /usr/local/bin/
    ```

    **Linux (arm64)**
    ```bash
    curl -LO https://github.com/robinmordasiewicz/vesctl/releases/download/{{ .Tag }}/vesctl_{{ .Version }}_linux_arm64.tar.gz
    tar -xzf vesctl_{{ .Version }}_linux_arm64.tar.gz
    sudo mv vesctl /usr/local/bin/
    ```

    **Windows (amd64)**
    Download `vesctl_{{ .Version }}_windows_amd64.zip` and extract to your PATH.

    **Windows (arm64)**
    Download `vesctl_{{ .Version }}_windows_arm64.zip` and extract to your PATH.
  footer: |
    **Full Changelog**: https://github.com/robinmordasiewicz/vesctl/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap
brews:
  - name: vesctl
    repository:
      owner: robinmordasiewicz
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: Update {{ .ProjectName }} formula to {{ .Tag }}"
    homepage: https://github.com/robinmordasiewicz/vesctl
    description: Command-line interface for F5 Distributed Cloud
    license: Apache-2.0
    install: |
      bin.install "vesctl"
    test: |
      system "#{bin}/vesctl", "version"
    caveats: |
      To get started with vesctl:
        1. Configure authentication: vesctl configure
        2. List namespaces: vesctl configuration list namespace
        3. Get help: vesctl --help
