# Markdownlint configuration
# Documentation: https://github.com/DavidAnson/markdownlint

# Default state for all rules
default: true

# Line length - disabled for HTML-heavy docs with inline SVGs
MD013: false

# Allow inline HTML (needed for some documentation features)
MD033: false

# Allow duplicate headings in different sections
MD024:
  siblings_only: true

# First line should be a top-level heading
MD041: true

# Allow bare URLs (common in CLIs)
MD034: false

# Ordered list item prefix - disabled due to code blocks breaking list context
MD029: false

# Code block style - disabled (conflicts with MkDocs tabbed content syntax)
MD046: false
