---
extends: default
rules:
  line-length:
    max: 200
    level: warning
  indentation:
    spaces: 2
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
ignore: |
  docs/commands/
  .specs/
