package types

// DomainInfo contains metadata about a resource domain
type DomainInfo struct {
	Name        string   // Canonical: "load_balancer"
	DisplayName string   // Human: "Load Balancer"
	Description string   // Functional description
	Aliases     []string // Short forms: ["lb"]

	// Fields from v1.0.43 upstream specs
	Complexity     string                 // Complexity level: "simple", "moderate", "advanced"
	IsPreview      bool                   // Whether this domain is in preview/beta
	RequiresTier   string                 // Required subscription tier
	Category       string                 // Domain category: "Security", "Platform", etc.
	UseCases       []string               // Use cases for this domain
	RelatedDomains []string               // Related domain names
	CLIMetadata    map[string]interface{} // CLI-specific metadata (quick_start, workflows, etc.)
}

// DomainRegistry and AliasRegistry are auto-generated in domains_generated.go
// Do not edit this file directly; run `make generate` to update from upstream specs

func init() {
	// Initialize AliasRegistry on startup
	for canonical, info := range DomainRegistry {
		// Map canonical name to itself
		AliasRegistry[canonical] = canonical
		// Map all aliases to canonical name
		for _, alias := range info.Aliases {
			AliasRegistry[alias] = canonical
		}
	}
}

// ResolveDomain converts an alias or canonical name to the canonical domain name
func ResolveDomain(nameOrAlias string) (string, bool) {
	canonical, ok := AliasRegistry[nameOrAlias]
	return canonical, ok
}

// GetDomainInfo retrieves domain metadata by canonical name or alias
func GetDomainInfo(nameOrAlias string) (*DomainInfo, bool) {
	canonical, ok := ResolveDomain(nameOrAlias)
	if !ok {
		return nil, false
	}
	info, found := DomainRegistry[canonical]
	return info, found
}

// AllDomains returns all canonical domain names in sorted order
func AllDomains() []string {
	domains := make([]string, 0, len(DomainRegistry))
	for domain := range DomainRegistry {
		domains = append(domains, domain)
	}
	return domains
}
