// Code generated by generate-examples.go. DO NOT EDIT.
// This file contains JSON examples for CLI help output.

package types

// resourceExamples maps resource names to their JSON example bodies.
// These examples are generated from OpenAPI specifications.
var resourceExamples = map[string]string{
	"address_allocator": `{
  "metadata": {
    "name": "example-address-allocator",
    "namespace": "example-namespace"
  },
  "spec": {
    "address_pool": [
      "example-value"
    ]
  }
}`,
	"advertise_policy": `{
  "metadata": {
    "name": "example-advertise-policy",
    "namespace": "example-namespace"
  },
  "spec": {
    "address": "10.1.2.3/2001::1.",
    "port": 80,
    "protocol": "TCP",
    "skip_xff_append": false
  }
}`,
	"alert_policy": `{
  "metadata": {
    "name": "example-alert-policy",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"alert_receiver": `{
  "metadata": {
    "name": "example-alert-receiver",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"api_definition": `{
  "metadata": {
    "name": "example-api-definition",
    "namespace": "example-namespace"
  },
  "spec": {
    "swagger_specs": [
      "example-value"
    ]
  }
}`,
	"app_api_group": `{
  "metadata": {
    "name": "example-app-api-group",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"app_firewall": `{
  "metadata": {
    "name": "example-app-firewall",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"app_type": `{
  "metadata": {
    "name": "example-app-type",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"authentication": `{
  "metadata": {
    "name": "example-authentication",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"aws_tgw_site": `{
  "metadata": {
    "name": "example-aws-tgw-site",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"aws_vpc_site": `{
  "metadata": {
    "name": "example-aws-vpc-site",
    "namespace": "example-namespace"
  },
  "spec": {
    "address": "123 Street, city, country, postal code.",
    "aws_region": "Us-east-1",
    "disk_size": 80,
    "instance_type": "a1.xlarge",
    "nodes_per_az": 2,
    "ssh_key": "SSH-rsa AAAAB..."
  }
}`,
	"azure_vnet_site": `{
  "metadata": {
    "name": "example-azure-vnet-site",
    "namespace": "example-namespace"
  },
  "spec": {
    "address": "123 Street, city, country, postal code.",
    "alternate_region": "Northcentralus.",
    "disk_size": 80,
    "machine_type": "Standard_D4s_v4.",
    "nodes_per_az": 2,
    "resource_group": "Example-resources.",
    "ssh_key": "SSH-rsa AAAAB..."
  }
}`,
	"bgp": `{
  "metadata": {
    "name": "example-bgp",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"bgp_asn_set": `{
  "metadata": {
    "name": "example-bgp-asn-set",
    "namespace": "example-namespace"
  },
  "spec": {
    "as_numbers": [
      1
    ]
  }
}`,
	"bigip_irule": `{
  "metadata": {
    "name": "example-bigip-irule",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"bot_defense_app_infrastructure": `{
  "metadata": {
    "name": "example-bot-defense-app-infrastructure",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"cdn_loadbalancer": `{
  "metadata": {
    "name": "example-cdn-loadbalancer",
    "namespace": "example-namespace"
  },
  "spec": {
    "app_firewall": {
      "name": "Contacts-route.",
      "namespace": "Ns1",
      "tenant": "Example-corp."
    },
    "domains": [
      "example-value"
    ],
    "http": {
      "port": 80
    },
    "origin_pool": {
      "origin_request_timeout": "100s"
    }
  }
}`,
	"certificate": `{
  "metadata": {
    "name": "example-certificate",
    "namespace": "example-namespace"
  },
  "spec": {
    "certificate_url": "Value"
  }
}`,
	"certificate_chain": `{
  "metadata": {
    "name": "example-certificate-chain",
    "namespace": "example-namespace"
  },
  "spec": {
    "certificate_url": "Value"
  }
}`,
	"cloud_credentials": `{
  "metadata": {
    "name": "example-cloud-credentials",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"cloud_elastic_ip": `{
  "metadata": {
    "name": "example-cloud-elastic-ip",
    "namespace": "example-namespace"
  },
  "spec": {
    "count": 3
  }
}`,
	"cluster": `{
  "metadata": {
    "name": "example-cluster",
    "namespace": "example-namespace"
  },
  "spec": {
    "connection_timeout": 4000,
    "http_idle_timeout": 60000
  }
}`,
	"cminstance": `{
  "metadata": {
    "name": "example-cminstance",
    "namespace": "example-namespace"
  },
  "spec": {
    "port": 443,
    "username": "Admin"
  }
}`,
	"contact": `{
  "metadata": {
    "name": "example-contact",
    "namespace": "example-namespace"
  },
  "spec": {
    "address1": "1234 Main road.",
    "address2": "P.O BOX 56.",
    "city": "Sunnyvale",
    "country": "US",
    "county": "Santa Clara.",
    "phone_number": "+11234567890.",
    "state": "California.",
    "state_code": "CA",
    "zip_code": "95054"
  }
}`,
	"container_registry": `{
  "metadata": {
    "name": "example-container-registry",
    "namespace": "example-namespace"
  },
  "spec": {
    "email": "Joe@gmail.com.",
    "registry": "Quay.I/O",
    "user_name": "Joe"
  }
}`,
	"crl": `{
  "metadata": {
    "name": "example-crl",
    "namespace": "example-namespace"
  },
  "spec": {
    "refresh_interval": 24,
    "server_address": "mycrl.it.com.",
    "server_port": 80,
    "timeout": 10
  }
}`,
	"data_type": `{
  "metadata": {
    "name": "example-data-type",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"dc_cluster_group": `{
  "metadata": {
    "name": "example-dc-cluster-group",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"discovery": `{
  "metadata": {
    "name": "example-discovery",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"dns_compliance_checks": `{
  "metadata": {
    "name": "example-dns-compliance-checks",
    "namespace": "example-namespace"
  },
  "spec": {
    "domain_denylist": [
      "example-value"
    ]
  }
}`,
	"dns_domain": `{
  "metadata": {
    "name": "example-dns-domain",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"dns_lb_health_check": `{
  "metadata": {
    "name": "example-dns-lb-health-check",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"dns_lb_pool": `{
  "metadata": {
    "name": "example-dns-lb-pool",
    "namespace": "example-namespace"
  },
  "spec": {
    "ttl": 3600
  }
}`,
	"dns_zone": `{
  "metadata": {
    "name": "example-dns-zone",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"external_connector": `{
  "metadata": {
    "name": "example-external-connector",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"fast_acl_rule": `{
  "metadata": {
    "name": "example-fast-acl-rule",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"filter_set": `{
  "metadata": {
    "name": "example-filter-set",
    "namespace": "example-namespace"
  },
  "spec": {
    "context_key": "example-value"
  }
}`,
	"forward_proxy_policy": `{
  "metadata": {
    "name": "example-forward-proxy-policy",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"forwarding_class": `{
  "metadata": {
    "name": "example-forwarding-class",
    "namespace": "example-namespace"
  },
  "spec": {
    "tos_value": 10
  }
}`,
	"gcp_vpc_site": `{
  "metadata": {
    "name": "example-gcp-vpc-site",
    "namespace": "example-namespace"
  },
  "spec": {
    "address": "123 Street, city, country, postal code.",
    "disk_size": 80,
    "gcp_region": "Us-west1",
    "instance_type": "N1-standard-4.",
    "ssh_key": "SSH-rsa AAAAB..."
  }
}`,
	"geo_location_set": `{
  "metadata": {
    "name": "example-geo-location-set",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"global_log_receiver": `{
  "metadata": {
    "name": "example-global-log-receiver",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"healthcheck": `{
  "metadata": {
    "name": "example-healthcheck",
    "namespace": "example-namespace"
  },
  "spec": {
    "healthy_threshold": 2,
    "interval": 10,
    "jitter_percent": 25,
    "timeout": 1,
    "unhealthy_threshold": 5
  }
}`,
	"http_loadbalancer": `{
  "metadata": {
    "name": "example-http-loadbalancer",
    "namespace": "example-namespace"
  },
  "spec": {
    "add_location": false,
    "app_firewall": {
      "name": "Contacts-route.",
      "namespace": "Ns1",
      "tenant": "Example-corp."
    },
    "default_pool": {
      "port": 9080
    },
    "domains": [
      "example-value"
    ],
    "http": {
      "port": 80
    }
  }
}`,
	"ike_phase1_profile": `{
  "metadata": {
    "name": "example-ike-phase1-profile",
    "namespace": "example-namespace"
  },
  "spec": {
    "authentication_algos": [
      "AUTH_ALG_DEFAULT"
    ],
    "dh_group": [
      "DH_GROUP_DEFAULT"
    ],
    "encryption_algos": [
      "ENC_ALG_DEFAULT"
    ],
    "prf": [
      "PRF_DEFAULT"
    ]
  }
}`,
	"ike_phase2_profile": `{
  "metadata": {
    "name": "example-ike-phase2-profile",
    "namespace": "example-namespace"
  },
  "spec": {
    "authentication_algos": [
      "AUTH_ALG_DEFAULT"
    ],
    "encryption_algos": [
      "ENC_ALG_DEFAULT"
    ]
  }
}`,
	"infraprotect_asn": `{
  "metadata": {
    "name": "example-infraprotect-asn",
    "namespace": "example-namespace"
  },
  "spec": {
    "asn": 12345
  }
}`,
	"infraprotect_asn_prefix": `{
  "metadata": {
    "name": "example-infraprotect-asn-prefix",
    "namespace": "example-namespace"
  },
  "spec": {
    "prefix": "10.10.10.0/24."
  }
}`,
	"infraprotect_deny_list_rule": `{
  "metadata": {
    "name": "example-infraprotect-deny-list-rule",
    "namespace": "example-namespace"
  },
  "spec": {
    "prefix": "12.13.14.0/24 or 12.13.14.15/32."
  }
}`,
	"infraprotect_firewall_rule": `{
  "metadata": {
    "name": "example-infraprotect-firewall-rule",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"infraprotect_firewall_rule_group": `{
  "metadata": {
    "name": "example-infraprotect-firewall-rule-group",
    "namespace": "example-namespace"
  },
  "spec": {
    "firewall_rule_group_name": "Group Name."
  }
}`,
	"infraprotect_internet_prefix_advertisement": `{
  "metadata": {
    "name": "example-infraprotect-internet-prefix-advertisement",
    "namespace": "example-namespace"
  },
  "spec": {
    "prefix": "12.12.0.0/24."
  }
}`,
	"infraprotect_tunnel": `{
  "metadata": {
    "name": "example-infraprotect-tunnel",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"ip_prefix_set": `{
  "metadata": {
    "name": "example-ip-prefix-set",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"k8s_cluster": `{
  "metadata": {
    "name": "example-k8s-cluster",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"k8s_cluster_role": `{
  "metadata": {
    "name": "example-k8s-cluster-role",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"k8s_cluster_role_binding": `{
  "metadata": {
    "name": "example-k8s-cluster-role-binding",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"k8s_pod_security_admission": `{
  "metadata": {
    "name": "example-k8s-pod-security-admission",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"k8s_pod_security_policy": `{
  "metadata": {
    "name": "example-k8s-pod-security-policy",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"log_receiver": `{
  "metadata": {
    "name": "example-log-receiver",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"malicious_user_mitigation": `{
  "metadata": {
    "name": "example-malicious-user-mitigation",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"nat_policy": `{
  "metadata": {
    "name": "example-nat-policy",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"network_connector": `{
  "metadata": {
    "name": "example-network-connector",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"network_firewall": `{
  "metadata": {
    "name": "example-network-firewall",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"network_interface": `{
  "metadata": {
    "name": "example-network-interface",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"network_policy_rule": `{
  "metadata": {
    "name": "example-network-policy-rule",
    "namespace": "example-namespace"
  },
  "spec": {
    "ports": [
      "example-value"
    ],
    "protocol": "TCP"
  }
}`,
	"network_policy_view": `{
  "metadata": {
    "name": "example-network-policy-view",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"origin_pool": `{
  "metadata": {
    "name": "example-origin-pool",
    "namespace": "example-namespace"
  },
  "spec": {
    "port": 9080,
    "use_tls": {
      "max_session_keys": 25
    }
  }
}`,
	"policer": `{
  "metadata": {
    "name": "example-policer",
    "namespace": "example-namespace"
  },
  "spec": {
    "burst_size": 10000,
    "committed_information_rate": 10000
  }
}`,
	"policy_based_routing": `{
  "metadata": {
    "name": "example-policy-based-routing",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"protocol_inspection": `{
  "metadata": {
    "name": "example-protocol-inspection",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"protocol_policer": `{
  "metadata": {
    "name": "example-protocol-policer",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"proxy": `{
  "metadata": {
    "name": "example-proxy",
    "namespace": "example-namespace"
  },
  "spec": {
    "connection_timeout": 4000
  }
}`,
	"rate_limiter": `{
  "metadata": {
    "name": "example-rate-limiter",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"rate_limiter_policy": `{
  "metadata": {
    "name": "example-rate-limiter-policy",
    "namespace": "example-namespace"
  },
  "spec": {
    "server_name": "database.production.customer.F5 Distributed cloud.us."
  }
}`,
	"report_config": `{
  "metadata": {
    "name": "example-report-config",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"role": `{
  "metadata": {
    "name": "example-role",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"secret_management_access": `{
  "metadata": {
    "name": "example-secret-management-access",
    "namespace": "example-namespace"
  },
  "spec": {
    "provider_name": "Vault_backend."
  }
}`,
	"securemesh_site": `{
  "metadata": {
    "name": "example-securemesh-site",
    "namespace": "example-namespace"
  },
  "spec": {
    "address": "123 Street, city, country, postal code.",
    "volterra_certified_hw": "Isv-8000-series-voltmesh.",
    "worker_nodes": [
      "example-value"
    ]
  }
}`,
	"securemesh_site_v2": `{
  "metadata": {
    "name": "example-securemesh-site-v2",
    "namespace": "example-namespace"
  },
  "spec": {
    "tunnel_dead_timeout": 0
  }
}`,
	"tcp_loadbalancer": `{
  "metadata": {
    "name": "example-tcp-loadbalancer",
    "namespace": "example-namespace"
  },
  "spec": {
    "domains": [
      "example-value"
    ],
    "idle_timeout": 2000,
    "listen_port": 0
  }
}`,
	"tenant_configuration": `{
  "metadata": {
    "name": "example-tenant-configuration",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"token": `{
  "metadata": {
    "name": "example-token",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"tpm_api_key": `{
  "metadata": {
    "name": "example-tpm-api-key",
    "namespace": "example-namespace"
  },
  "spec": {
    "need_mtls": false
  }
}`,
	"tpm_category": `{
  "metadata": {
    "name": "example-tpm-category",
    "namespace": "example-namespace"
  },
  "spec": {
    "tpm_allow_list": [
      "example-value"
    ]
  }
}`,
	"tpm_manager": `{
  "metadata": {
    "name": "example-tpm-manager",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"trusted_ca_list": `{
  "metadata": {
    "name": "example-trusted-ca-list",
    "namespace": "example-namespace"
  },
  "spec": {
    "trusted_ca_url": "Cert"
  }
}`,
	"udp_loadbalancer": `{
  "metadata": {
    "name": "example-udp-loadbalancer",
    "namespace": "example-namespace"
  },
  "spec": {
    "domains": [
      "example-value"
    ],
    "idle_timeout": 2000,
    "listen_port": 53
  }
}`,
	"usb_policy": `{
  "metadata": {
    "name": "example-usb-policy",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"user_identification": `{
  "metadata": {
    "name": "example-user-identification",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"virtual_k8s": `{
  "metadata": {
    "name": "example-virtual-k8s",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"virtual_network": `{
  "metadata": {
    "name": "example-virtual-network",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"voltstack_site": `{
  "metadata": {
    "name": "example-voltstack-site",
    "namespace": "example-namespace"
  },
  "spec": {
    "address": "123 Street, city, country, postal code.",
    "volterra_certified_hw": "Isv-8000-series-voltstack-combo.",
    "worker_nodes": [
      "example-value"
    ]
  }
}`,
	"workload": `{
  "metadata": {
    "name": "example-workload",
    "namespace": "example-namespace"
  },
  "spec": {}
}`,
	"workload_flavor": `{
  "metadata": {
    "name": "example-workload-flavor",
    "namespace": "example-namespace"
  },
  "spec": {
    "ephemeral_storage": "100",
    "memory": "500",
    "vcpus": 1
  }
}`,
}

// GetResourceExample returns the JSON example for a resource type.
// Returns empty string if no example is available.
func GetResourceExample(resourceName string) string {
	return resourceExamples[resourceName]
}
