/**
 * Shell Completion Generators
 *
 * Generate completion scripts for bash, zsh, and fish shells.
 * Uses the unified CompletionRegistry for consistent behavior.
 */

/* eslint-disable no-useless-escape */
// Note: \$ escapes are required in template strings to generate shell scripts
// where $ is a literal character, not a template interpolation

import { completionRegistry } from "../../completion/index.js";
import {
	escapeForZsh,
	escapeForFish,
	getActionDescriptions,
} from "../../completion/index.js";

/**
 * Generate Bash completion script
 */
export function generateBashCompletion(): string {
	const domains = completionRegistry.getDomains();
	const domainNames = domains.map((d) => d.name).join(" ");

	// Collect all aliases
	const allAliases: string[] = [];
	for (const domain of domains) {
		if (domain.aliases) {
			allAliases.push(...domain.aliases);
		}
	}

	// Get actions from the registry
	const actionDescriptions = getActionDescriptions();
	const actions = Object.keys(actionDescriptions).join(" ");

	// Build custom domain completions (domains with custom children structure)
	const customDomainCompletions: string[] = [];
	for (const domain of domains) {
		if (domain.source !== "custom" || !domain.children) continue;

		// Collect all child names (commands and subcommand groups)
		const childNames = Array.from(domain.children.keys());
		if (childNames.length > 0) {
			customDomainCompletions.push(
				`        ${domain.name})`,
				`          COMPREPLY=($(compgen -W "${childNames.join(" ")}" -- "\${cur}"))`,
				`          return 0`,
				`          ;;`,
			);
		}

		// Add nested subcommand groups
		for (const [childName, child] of domain.children) {
			if (child.children && child.children.size > 0) {
				const nestedNames = Array.from(child.children.keys());
				customDomainCompletions.push(
					`        ${domain.name}/${childName})`,
					`          COMPREPLY=($(compgen -W "${nestedNames.join(" ")}" -- "\${cur}"))`,
					`          return 0`,
					`          ;;`,
				);
			}
		}
	}

	return `# bash completion for xcsh
# Generated by xcsh completion bash
# shellcheck disable=SC2034,SC2207

_xcsh_completions() {
  local cur prev words cword
  _init_completion || return

  local commands="${domainNames} ${allAliases.join(" ")} help quit exit clear history"
  local actions="${actions}"
  local builtins="help quit exit clear history context ctx"
  local global_flags="--help -h --version -v --interactive -i --no-color --output -o --namespace -ns"

  # Handle completion based on position
  case \${cword} in
    1)
      # First word: domains, builtins, or flags
      if [[ "\${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "\${global_flags}" -- "\${cur}"))
      else
        COMPREPLY=($(compgen -W "\${commands} \${builtins}" -- "\${cur}"))
      fi
      return 0
      ;;
    2)
      # Second word: actions or subcommands based on first word
      local domain="\${words[1]}"
      case "\${domain}" in
${customDomainCompletions.join("\n")}
        help | quit | exit | clear | history | context | ctx)
          return 0
          ;;
        *)
          # API domain - suggest actions
          COMPREPLY=($(compgen -W "\${actions}" -- "\${cur}"))
          return 0
          ;;
      esac
      ;;
    *)
      # Third+ word: flags
      if [[ "\${cur}" == -* ]]; then
        local action_flags="--name -n --namespace -ns --output -o --json --yaml --limit --label"
        COMPREPLY=($(compgen -W "\${action_flags}" -- "\${cur}"))
      fi
      return 0
      ;;
  esac
}

complete -F _xcsh_completions xcsh
`;
}

/**
 * Generate Zsh completion script
 */
export function generateZshCompletion(): string {
	const domains = completionRegistry.getDomains();

	// Build domain descriptions for zsh
	const domainDescriptions = domains
		.map((d) => {
			const escaped = escapeForZsh(d.description);
			return `'${d.name}:${escaped}'`;
		})
		.join("\n            ");

	// Build alias descriptions
	const aliasDescriptions = domains
		.filter((d) => d.aliases && d.aliases.length > 0)
		.flatMap((d) => d.aliases!.map((a) => `'${a}:Alias for ${d.name}'`))
		.join("\n            ");

	// Build action descriptions
	const actionDescriptions = getActionDescriptions();
	const actionDescArray = Object.entries(actionDescriptions)
		.map(([action, desc]) => {
			const escaped = escapeForZsh(desc);
			return `'${action}:${escaped}'`;
		})
		.join("\n            ");

	// Build custom domain completions with actual descriptions
	const customDomainCompletions: string[] = [];
	for (const domain of domains) {
		if (domain.source !== "custom" || !domain.children) continue;

		const childDescriptions: string[] = [];
		for (const child of domain.children.values()) {
			const escaped = escapeForZsh(child.description);
			childDescriptions.push(`'${child.name}:${escaped}'`);
		}

		if (childDescriptions.length > 0) {
			customDomainCompletions.push(
				`        (${domain.name})`,
				`            _values 'command' ${childDescriptions.join(" ")}`,
				`            ;;`,
			);
		}
	}

	return `#compdef xcsh
# zsh completion for xcsh
# Generated by xcsh completion zsh

_xcsh() {
    local curcontext="\$curcontext" state line
    typeset -A opt_args

    local -a global_opts
    global_opts=(
        '(-h --help)'{-h,--help}'[Show help information]'
        '(-v --version)'{-v,--version}'[Show version number]'
        '(-i --interactive)'{-i,--interactive}'[Force interactive mode]'
        '--no-color[Disable color output]'
        '(-o --output)'{-o,--output}'[Output format]:format:(json yaml table)'
        '(-ns --namespace)'{-ns,--namespace}'[Namespace]:namespace:_xcsh_namespaces'
    )

    _arguments -C \\
        "\${global_opts[@]}" \\
        '1: :->domain' \\
        '2: :->action' \\
        '*: :->args'

    case \$state in
        (domain)
            local -a domains builtins
            domains=(
            ${domainDescriptions}
            ${aliasDescriptions}
            )
            builtins=(
                'help:Show help information'
                'quit:Exit the shell'
                'exit:Exit the shell'
                'clear:Clear the screen'
                'history:Show command history'
                'context:Show current navigation context'
                'ctx:Show current navigation context'
            )
            _describe -t domains 'domain' domains
            _describe -t builtins 'builtin' builtins
            ;;
        (action)
            case \${line[1]} in
${customDomainCompletions.join("\n")}
                (help|quit|exit|clear|history|context|ctx)
                    ;;
                (*)
                    local -a actions
                    actions=(
            ${actionDescArray}
                    )
                    _describe -t actions 'action' actions
                    ;;
            esac
            ;;
        (args)
            local -a action_opts
            action_opts=(
                '(-n --name)'{-n,--name}'[Resource name]:name:'
                '(-ns --namespace)'{-ns,--namespace}'[Namespace]:namespace:_xcsh_namespaces'
                '(-o --output)'{-o,--output}'[Output format]:format:(json yaml table)'
                '--limit[Maximum results]:limit:'
                '--label[Filter by label]:label:'
                '(-f --file)'{-f,--file}'[Configuration file]:file:_files'
            )
            _arguments "\${action_opts[@]}"
            ;;
    esac
}

_xcsh_namespaces() {
    local -a namespaces
    namespaces=('default' 'system' 'shared')
    _describe -t namespaces 'namespace' namespaces
}

_xcsh "\$@"
`;
}

/**
 * Generate Fish completion script
 */
export function generateFishCompletion(): string {
	const domains = completionRegistry.getDomains();
	const actionDescriptions = getActionDescriptions();

	// Build domain completions
	const domainCompletions = domains
		.map((d) => {
			const escaped = escapeForFish(d.description);
			return `complete -c xcsh -n "__fish_use_subcommand" -a "${d.name}" -d '${escaped}'`;
		})
		.join("\n");

	// Build alias completions
	const aliasCompletions = domains
		.filter((d) => d.aliases && d.aliases.length > 0)
		.flatMap((d) =>
			d.aliases!.map(
				(a) =>
					`complete -c xcsh -n "__fish_use_subcommand" -a "${a}" -d 'Alias for ${d.name}'`,
			),
		)
		.join("\n");

	// Build custom domain subcommand completions
	const customDomainCompletions: string[] = [];
	for (const domain of domains) {
		if (domain.source !== "custom" || !domain.children) continue;

		for (const child of domain.children.values()) {
			const escaped = escapeForFish(child.description);
			customDomainCompletions.push(
				`complete -c xcsh -n "__fish_seen_subcommand_from ${domain.name}" -a "${child.name}" -d '${escaped}'`,
			);

			// Nested commands within subcommand groups
			if (child.children) {
				for (const nested of child.children.values()) {
					const nestedEscaped = escapeForFish(nested.description);
					customDomainCompletions.push(
						`complete -c xcsh -n "__fish_seen_subcommand_from ${domain.name}; and __fish_seen_subcommand_from ${child.name}" -a "${nested.name}" -d '${nestedEscaped}'`,
					);
				}
			}
		}
	}

	// Build action completions for API domains
	const apiDomains = domains.filter((d) => d.source === "api");
	const actionCompletions = apiDomains
		.map((d) =>
			Object.entries(actionDescriptions)
				.map(
					([action, desc]) =>
						`complete -c xcsh -n "__fish_seen_subcommand_from ${d.name}" -a "${action}" -d '${escapeForFish(desc)}'`,
				)
				.join("\n"),
		)
		.join("\n");

	return `# fish completion for xcsh
# Generated by xcsh completion fish

# Disable file completions for xcsh
complete -c xcsh -f

# Global options
complete -c xcsh -s h -l help -d 'Show help information'
complete -c xcsh -s v -l version -d 'Show version number'
complete -c xcsh -s i -l interactive -d 'Force interactive mode'
complete -c xcsh -l no-color -d 'Disable color output'
complete -c xcsh -s o -l output -d 'Output format' -xa 'json yaml table'
complete -c xcsh -l namespace -s ns -d 'Namespace' -xa 'default system shared'

# Builtin commands
complete -c xcsh -n "__fish_use_subcommand" -a "help" -d 'Show help information'
complete -c xcsh -n "__fish_use_subcommand" -a "quit" -d 'Exit the shell'
complete -c xcsh -n "__fish_use_subcommand" -a "exit" -d 'Exit the shell'
complete -c xcsh -n "__fish_use_subcommand" -a "clear" -d 'Clear the screen'
complete -c xcsh -n "__fish_use_subcommand" -a "history" -d 'Show command history'
complete -c xcsh -n "__fish_use_subcommand" -a "context" -d 'Show current navigation context'
complete -c xcsh -n "__fish_use_subcommand" -a "ctx" -d 'Show current navigation context'

# Domain completions
${domainCompletions}

# Alias completions
${aliasCompletions}

# Custom domain subcommands
${customDomainCompletions.join("\n")}

# Action completions for API domains
${actionCompletions}

# Action-specific flags
complete -c xcsh -l name -s n -d 'Resource name'
complete -c xcsh -l limit -d 'Maximum results'
complete -c xcsh -l label -d 'Filter by label'
complete -c xcsh -s f -l file -d 'Configuration file' -r
complete -c xcsh -l force -d 'Force deletion'
complete -c xcsh -l cascade -d 'Cascade delete'
`;
}
