/**
 * Shell Completion Generators
 * Generate completion scripts for bash, zsh, and fish shells
 */

/* eslint-disable no-useless-escape */
// Note: \$ escapes are required in template strings to generate shell scripts
// where $ is a literal character, not a template interpolation

import { domainRegistry, validActions } from "../../types/domains.js";
import { customDomains } from "../registry.js";
import { extensionRegistry } from "../../extensions/index.js";

/**
 * Get all completable domains (API + custom + extension)
 */
function getAllDomains(): Array<{
	name: string;
	description: string;
	aliases: string[];
}> {
	const domains: Array<{
		name: string;
		description: string;
		aliases: string[];
	}> = [];
	const seen = new Set<string>();

	// Custom domains first (highest priority)
	for (const domain of customDomains.all()) {
		domains.push({
			name: domain.name,
			description: domain.description,
			aliases: [],
		});
		seen.add(domain.name);
	}

	// Extension-only domains
	for (const extDomain of extensionRegistry.getExtendedDomains()) {
		if (seen.has(extDomain)) continue;
		if (domainRegistry.has(extDomain)) continue;

		const merged = extensionRegistry.getMergedDomain(extDomain);
		if (merged && merged.source === "extension") {
			domains.push({
				name: extDomain,
				description: merged.description,
				aliases: [],
			});
			seen.add(extDomain);
		}
	}

	// API-generated domains
	for (const [name, info] of domainRegistry) {
		if (seen.has(name)) continue;
		domains.push({
			name,
			description: info.description,
			aliases: info.aliases,
		});
		seen.add(name);
	}

	return domains.sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Get custom domain commands and subcommands for completion
 */
function getCustomDomainCommands(domainName: string): {
	commands: string[];
	subcommands: Map<string, string[]>;
} {
	const domain = customDomains.get(domainName);
	if (!domain) {
		return { commands: [], subcommands: new Map() };
	}

	const commands = Array.from(domain.commands.keys());
	const subcommands = new Map<string, string[]>();

	for (const [groupName, group] of domain.subcommands) {
		subcommands.set(groupName, Array.from(group.commands.keys()));
	}

	return { commands, subcommands };
}

/**
 * Generate Bash completion script
 */
export function generateBashCompletion(): string {
	const domains = getAllDomains();
	const domainNames = domains.map((d) => d.name).join(" ");
	const allAliases = domains.flatMap((d) => d.aliases).join(" ");
	const actions = Array.from(validActions).join(" ");

	// Build custom domain completions
	const customDomainCompletions: string[] = [];
	for (const domain of customDomains.all()) {
		const { commands, subcommands } = getCustomDomainCommands(domain.name);

		// Direct commands for domain
		if (commands.length > 0 || subcommands.size > 0) {
			const allCommands = [
				...commands,
				...Array.from(subcommands.keys()),
			];
			customDomainCompletions.push(
				`        ${domain.name})`,
				`            COMPREPLY=( $(compgen -W "${allCommands.join(" ")}" -- "\${cur}") )`,
				`            return 0`,
				`            ;;`,
			);
		}

		// Subcommand groups
		for (const [groupName, groupCommands] of subcommands) {
			customDomainCompletions.push(
				`        ${domain.name}/${groupName})`,
				`            COMPREPLY=( $(compgen -W "${groupCommands.join(" ")}" -- "\${cur}") )`,
				`            return 0`,
				`            ;;`,
			);
		}
	}

	return `# bash completion for xcsh
# Generated by xcsh completion bash
# shellcheck disable=SC2034,SC2207

_xcsh_completions() {
    local cur prev words cword
    _init_completion || return

    local commands="${domainNames} ${allAliases} help quit exit clear history"
    local actions="${actions}"
    local builtins="help quit exit clear history context ctx"
    local global_flags="--help -h --version -v --interactive -i --no-color --output -o --namespace -ns"

    # Handle completion based on position
    case \${cword} in
        1)
            # First word: domains, builtins, or flags
            if [[ "\${cur}" == -* ]]; then
                COMPREPLY=( $(compgen -W "\${global_flags}" -- "\${cur}") )
            else
                COMPREPLY=( $(compgen -W "\${commands} \${builtins}" -- "\${cur}") )
            fi
            return 0
            ;;
        2)
            # Second word: actions or subcommands based on first word
            local domain="\${words[1]}"
            case "\${domain}" in
${customDomainCompletions.join("\n")}
                help|quit|exit|clear|history|context|ctx)
                    return 0
                    ;;
                *)
                    # API domain - suggest actions
                    COMPREPLY=( $(compgen -W "\${actions}" -- "\${cur}") )
                    return 0
                    ;;
            esac
            ;;
        *)
            # Third+ word: flags
            if [[ "\${cur}" == -* ]]; then
                local action_flags="--name -n --namespace -ns --output -o --json --yaml --limit --label"
                COMPREPLY=( $(compgen -W "\${action_flags}" -- "\${cur}") )
            fi
            return 0
            ;;
    esac
}

complete -F _xcsh_completions xcsh
`;
}

/**
 * Generate Zsh completion script
 */
export function generateZshCompletion(): string {
	const domains = getAllDomains();

	// Build domain descriptions for zsh
	const domainDescriptions = domains
		.map((d) => {
			const escaped = d.description
				.replace(/'/g, "'\\''")
				.replace(/:/g, "\\:");
			return `'${d.name}:${escaped}'`;
		})
		.join("\n            ");

	// Build alias descriptions
	const aliasDescriptions = domains
		.flatMap((d) => d.aliases.map((a) => `'${a}:Alias for ${d.name}'`))
		.join("\n            ");

	// Build action descriptions
	const actionDescriptions = [
		"'list:List resources'",
		"'get:Get a specific resource'",
		"'create:Create a new resource'",
		"'delete:Delete a resource'",
		"'replace:Replace a resource'",
		"'apply:Apply configuration from file'",
		"'status:Get resource status'",
		"'patch:Patch a resource'",
		"'add-labels:Add labels to a resource'",
		"'remove-labels:Remove labels from a resource'",
	].join("\n            ");

	// Build custom domain completions
	const customDomainCompletions: string[] = [];
	for (const domain of customDomains.all()) {
		const { commands, subcommands } = getCustomDomainCommands(domain.name);

		if (commands.length > 0 || subcommands.size > 0) {
			const cmdDescriptions = commands
				.map((c) => `'${c}:Command'`)
				.join(" ");
			const subDescriptions = Array.from(subcommands.keys())
				.map((s) => `'${s}:Subcommand group'`)
				.join(" ");

			customDomainCompletions.push(
				`        (${domain.name})`,
				`            _values 'command' ${cmdDescriptions} ${subDescriptions}`,
				`            ;;`,
			);
		}
	}

	return `#compdef xcsh
# zsh completion for xcsh
# Generated by xcsh completion zsh

_xcsh() {
    local curcontext="\$curcontext" state line
    typeset -A opt_args

    local -a global_opts
    global_opts=(
        '(-h --help)'{-h,--help}'[Show help information]'
        '(-v --version)'{-v,--version}'[Show version number]'
        '(-i --interactive)'{-i,--interactive}'[Force interactive mode]'
        '--no-color[Disable color output]'
        '(-o --output)'{-o,--output}'[Output format]:format:(json yaml table)'
        '(-ns --namespace)'{-ns,--namespace}'[Namespace]:namespace:_xcsh_namespaces'
    )

    _arguments -C \\
        "\${global_opts[@]}" \\
        '1: :->domain' \\
        '2: :->action' \\
        '*: :->args'

    case \$state in
        (domain)
            local -a domains builtins
            domains=(
            ${domainDescriptions}
            ${aliasDescriptions}
            )
            builtins=(
                'help:Show help information'
                'quit:Exit the shell'
                'exit:Exit the shell'
                'clear:Clear the screen'
                'history:Show command history'
                'context:Show current navigation context'
                'ctx:Show current navigation context'
            )
            _describe -t domains 'domain' domains
            _describe -t builtins 'builtin' builtins
            ;;
        (action)
            case \${line[1]} in
${customDomainCompletions.join("\n")}
                (help|quit|exit|clear|history|context|ctx)
                    ;;
                (*)
                    local -a actions
                    actions=(
            ${actionDescriptions}
                    )
                    _describe -t actions 'action' actions
                    ;;
            esac
            ;;
        (args)
            local -a action_opts
            action_opts=(
                '(-n --name)'{-n,--name}'[Resource name]:name:'
                '(-ns --namespace)'{-ns,--namespace}'[Namespace]:namespace:_xcsh_namespaces'
                '(-o --output)'{-o,--output}'[Output format]:format:(json yaml table)'
                '--limit[Maximum results]:limit:'
                '--label[Filter by label]:label:'
                '(-f --file)'{-f,--file}'[Configuration file]:file:_files'
            )
            _arguments "\${action_opts[@]}"
            ;;
    esac
}

_xcsh_namespaces() {
    local -a namespaces
    namespaces=('default' 'system' 'shared')
    _describe -t namespaces 'namespace' namespaces
}

_xcsh "\$@"
`;
}

/**
 * Generate Fish completion script
 */
export function generateFishCompletion(): string {
	const domains = getAllDomains();
	const actions = Array.from(validActions);

	// Build domain completions
	const domainCompletions = domains
		.map((d) => {
			const escaped = d.description.replace(/'/g, "\\'");
			return `complete -c xcsh -n "__fish_use_subcommand" -a "${d.name}" -d '${escaped}'`;
		})
		.join("\n");

	// Build alias completions
	const aliasCompletions = domains
		.flatMap((d) =>
			d.aliases.map(
				(a) =>
					`complete -c xcsh -n "__fish_use_subcommand" -a "${a}" -d 'Alias for ${d.name}'`,
			),
		)
		.join("\n");

	// Build action completions for each domain
	const actionCompletions = domains
		.map((d) =>
			actions
				.map(
					(a) =>
						`complete -c xcsh -n "__fish_seen_subcommand_from ${d.name}" -a "${a}" -d '${a.charAt(0).toUpperCase() + a.slice(1)} resources'`,
				)
				.join("\n"),
		)
		.join("\n");

	// Build custom domain subcommand completions
	const customDomainCompletions: string[] = [];
	for (const domain of customDomains.all()) {
		const { commands, subcommands } = getCustomDomainCommands(domain.name);

		// Direct commands
		for (const cmd of commands) {
			customDomainCompletions.push(
				`complete -c xcsh -n "__fish_seen_subcommand_from ${domain.name}" -a "${cmd}" -d 'Command'`,
			);
		}

		// Subcommand groups
		for (const [groupName, groupCommands] of subcommands) {
			customDomainCompletions.push(
				`complete -c xcsh -n "__fish_seen_subcommand_from ${domain.name}" -a "${groupName}" -d 'Subcommand group'`,
			);
			// Commands within subcommand groups
			for (const cmd of groupCommands) {
				customDomainCompletions.push(
					`complete -c xcsh -n "__fish_seen_subcommand_from ${domain.name}; and __fish_seen_subcommand_from ${groupName}" -a "${cmd}" -d 'Command'`,
				);
			}
		}
	}

	return `# fish completion for xcsh
# Generated by xcsh completion fish

# Disable file completions for xcsh
complete -c xcsh -f

# Global options
complete -c xcsh -s h -l help -d 'Show help information'
complete -c xcsh -s v -l version -d 'Show version number'
complete -c xcsh -s i -l interactive -d 'Force interactive mode'
complete -c xcsh -l no-color -d 'Disable color output'
complete -c xcsh -s o -l output -d 'Output format' -xa 'json yaml table'
complete -c xcsh -l namespace -s ns -d 'Namespace' -xa 'default system shared'

# Builtin commands
complete -c xcsh -n "__fish_use_subcommand" -a "help" -d 'Show help information'
complete -c xcsh -n "__fish_use_subcommand" -a "quit" -d 'Exit the shell'
complete -c xcsh -n "__fish_use_subcommand" -a "exit" -d 'Exit the shell'
complete -c xcsh -n "__fish_use_subcommand" -a "clear" -d 'Clear the screen'
complete -c xcsh -n "__fish_use_subcommand" -a "history" -d 'Show command history'
complete -c xcsh -n "__fish_use_subcommand" -a "context" -d 'Show current navigation context'
complete -c xcsh -n "__fish_use_subcommand" -a "ctx" -d 'Show current navigation context'

# Domain completions
${domainCompletions}

# Alias completions
${aliasCompletions}

# Custom domain subcommands
${customDomainCompletions.join("\n")}

# Action completions for API domains
${actionCompletions}

# Action-specific flags
complete -c xcsh -l name -s n -d 'Resource name'
complete -c xcsh -l limit -d 'Maximum results'
complete -c xcsh -l label -d 'Filter by label'
complete -c xcsh -s f -l file -d 'Configuration file' -r
complete -c xcsh -l force -d 'Force deletion'
complete -c xcsh -l cascade -d 'Cascade delete'
`;
}
