# golangci-lint v2 configuration
# Documentation: https://golangci-lint.run/usage/configuration/
# Migration guide: https://golangci-lint.run/docs/product/migration-guide/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Report suspicious constructs
    - ineffassign   # Detect ineffective assignments
    - staticcheck   # Static analysis checks (includes gosimple)
    - unused        # Check for unused code
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
  exclusions:
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - errcheck
