#!/usr/bin/env npx tsx
/**
 * Logo Asset Generator Script
 * Downloads F5 SVG logo, converts to PNG, and generates TypeScript module with base64 data.
 *
 * Run: npx tsx scripts/generate-logo-asset.ts
 */

import * as fs from "fs";
import * as path from "path";
import sharp from "sharp";

// F5 Logo SVG URL
const LOGO_SVG_URL =
	"https://media.ffycdn.net/us/f5-networks-inc/qi443UWRoMTME9ELdEsJ.svg";

// Output configuration
const OUTPUT_DIR = path.join(process.cwd(), "src", "branding");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "logo-image.ts");

// Image dimensions (pixels) - will be scaled to fit terminal cells
const TARGET_WIDTH = 240;
const TARGET_HEIGHT = 240;

// Suggested display dimensions in character cells
// Matches visual size of ASCII art logo circle (accounting for leading whitespace)
const DISPLAY_WIDTH = 45; // Character cells (matches ASCII logo visual width)
const DISPLAY_HEIGHT = 18; // Character cells (adjusted to eliminate dead space below image)

/**
 * Fetch the SVG from URL
 */
async function fetchSvg(url: string): Promise<Buffer> {
	console.log(`Fetching SVG from: ${url}`);

	const response = await fetch(url);
	if (!response.ok) {
		throw new Error(`Failed to fetch SVG: ${response.status} ${response.statusText}`);
	}

	const svgText = await response.text();
	return Buffer.from(svgText, "utf-8");
}

/**
 * Convert SVG to PNG using sharp
 */
async function convertSvgToPng(svgBuffer: Buffer): Promise<Buffer> {
	console.log(`Converting SVG to PNG (${TARGET_WIDTH}x${TARGET_HEIGHT})`);

	return await sharp(svgBuffer)
		.resize(TARGET_WIDTH, TARGET_HEIGHT, {
			fit: "contain",
			background: { r: 0, g: 0, b: 0, alpha: 0 }, // Transparent background
		})
		.png()
		.toBuffer();
}

/**
 * Generate TypeScript module content
 */
function generateTypeScriptModule(base64Data: string): string {
	const timestamp = new Date().toISOString();

	return `/**
 * F5 Logo as base64-encoded PNG for iTerm2 inline images.
 * AUTO-GENERATED by scripts/generate-logo-asset.ts - DO NOT EDIT
 *
 * Generated: ${timestamp}
 * Source: ${LOGO_SVG_URL}
 * Dimensions: ${TARGET_WIDTH}x${TARGET_HEIGHT} pixels
 */

/**
 * Base64-encoded PNG data for the F5 logo.
 * Use with iTerm2 inline images protocol or similar terminal graphics.
 */
export const F5_LOGO_PNG_BASE64 = "${base64Data}";

/**
 * Suggested display width in terminal character cells.
 * Matches the ASCII art logo visual width for consistency.
 */
export const F5_LOGO_DISPLAY_WIDTH = ${DISPLAY_WIDTH};

/**
 * Suggested display height in terminal character cells.
 * Terminal cells are typically ~2:1 aspect ratio (taller than wide).
 * Height = width / 2 to maintain square aspect ratio.
 */
export const F5_LOGO_DISPLAY_HEIGHT = ${DISPLAY_HEIGHT};

/**
 * Original image dimensions in pixels.
 */
export const F5_LOGO_PIXEL_WIDTH = ${TARGET_WIDTH};
export const F5_LOGO_PIXEL_HEIGHT = ${TARGET_HEIGHT};
`;
}

/**
 * Main function
 */
async function main(): Promise<void> {
	console.log("=== F5 Logo Asset Generator ===\n");

	try {
		// Step 1: Fetch SVG
		const svgBuffer = await fetchSvg(LOGO_SVG_URL);
		console.log(`  SVG fetched: ${svgBuffer.length} bytes`);

		// Step 2: Convert to PNG
		const pngBuffer = await convertSvgToPng(svgBuffer);
		console.log(`  PNG created: ${pngBuffer.length} bytes`);

		// Step 3: Base64 encode
		const base64Data = pngBuffer.toString("base64");
		console.log(`  Base64 encoded: ${base64Data.length} characters`);

		// Step 4: Generate TypeScript module
		const moduleContent = generateTypeScriptModule(base64Data);

		// Step 5: Ensure output directory exists
		if (!fs.existsSync(OUTPUT_DIR)) {
			fs.mkdirSync(OUTPUT_DIR, { recursive: true });
		}

		// Step 6: Write output file
		fs.writeFileSync(OUTPUT_FILE, moduleContent, "utf-8");
		console.log(`\n  Generated: ${OUTPUT_FILE}`);

		// Summary
		const fileSizeKb = (fs.statSync(OUTPUT_FILE).size / 1024).toFixed(2);
		console.log(`\n=== Complete ===`);
		console.log(`  Output file size: ${fileSizeKb} KB`);
		console.log(`  Display dimensions: ${DISPLAY_WIDTH}x${DISPLAY_HEIGHT} cells`);
	} catch (error) {
		console.error("\nError generating logo asset:", error);
		process.exit(1);
	}
}

main();
