# bash completion for xcsh
# Generated by xcsh completion bash
# shellcheck disable=SC2034,SC2207

_xcsh_completions() {
  local cur prev words cword
  _init_completion || return

  local commands="admin_console_and_ui api authentication bigip billing_and_usage blindfold bot_and_threat_defense cdn ce_management certificates cloud_infrastructure cloudstatus completion container_services data_and_privacy_security data_intelligence ddos dns generative_ai login managed_kubernetes marketplace network network_security nginx_one object_storage observability rate_limiting secops_and_incident_response service_mesh shape sites statistics support telemetry_and_insights tenant_and_identity threat_campaign users virtual vpm_and_node_management waf apisec api-discovery authn oidc sso f5-bigip irule ltm bf encrypt secrets cache content cert certs ssl tls cloud infra provider vk8s containers workloads di intelligence insights dos ddos-protect dns-zone zones ai genai assistant mk8s appstack k8s-mgmt market addons extensions net routing bgp netsec nfw nginx nms nginx-plus storage s3 buckets obs monitoring synth ratelimit throttle policer mesh svc-mesh shape-sec safeap site deployment stats metrics logs tickets help-desk telemetry ti threats campaigns threat-intel user accounts iam lb loadbalancer vhost vpm nodes node-mgmt firewall appfw help quit exit clear history"
  local actions="list get create delete replace apply status patch add-labels remove-labels"
  local builtins="help quit exit clear history context ctx"
  local global_flags="--help -h --version -v --interactive -i --no-color --output -o --namespace -ns"

  # Handle completion based on position
  case ${cword} in
    1)
      # First word: domains, builtins, or flags
      if [[ "${cur}" == -* ]]; then
        COMPREPLY=($(compgen -W "${global_flags}" -- "${cur}"))
      else
        COMPREPLY=($(compgen -W "${commands} ${builtins}" -- "${cur}"))
      fi
      return 0
      ;;
    2)
      # Second word: actions or subcommands based on first word
      local domain="${words[1]}"
      case "${domain}" in
        cloudstatus)
          COMPREPLY=($(compgen -W "status summary components incidents maintenance" -- "${cur}"))
          return 0
          ;;
        completion)
          COMPREPLY=($(compgen -W "bash zsh fish" -- "${cur}"))
          return 0
          ;;
        login)
          COMPREPLY=($(compgen -W "banner profile context" -- "${cur}"))
          return 0
          ;;
        login/profile)
          COMPREPLY=($(compgen -W "list show create use delete" -- "${cur}"))
          return 0
          ;;
        login/context)
          COMPREPLY=($(compgen -W "show set list" -- "${cur}"))
          return 0
          ;;
        help | quit | exit | clear | history | context | ctx)
          return 0
          ;;
        *)
          # API domain - suggest actions
          COMPREPLY=($(compgen -W "${actions}" -- "${cur}"))
          return 0
          ;;
      esac
      ;;
    *)
      # Third+ word: flags
      if [[ "${cur}" == -* ]]; then
        local action_flags="--name -n --namespace -ns --output -o --json --yaml --limit --label"
        COMPREPLY=($(compgen -W "${action_flags}" -- "${cur}"))
      fi
      return 0
      ;;
  esac
}

complete -F _xcsh_completions xcsh
